title: blog
description: some content is here
url: https://tiehuis.github.io
author: Marc Tiehuis

highlighter: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

permalink: /:title
gems:
  - jekyll-feed
  - jekyll-last-modified-at
